frontend/models/Comment.php
<?php

namespace frontend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%comment}}".
 *
 * @property int $id
 * @property int $page_id
 * @property int $created_at
 * @property string $message
 *
 * @property Page $page
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%comment}}';
    }
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['page_id'], 'required'],
            [['page_id'], 'integer'],
            [['message'], 'trim'],
            [['message'], 'filter', 'filter' => function($value){
                return \yii\helpers\HtmlPurifier::process($value);
            }],
            [['message'], 'string', 'max' => 255],
            [['page_id'], 'exist', 'skipOnError' => true, 'targetClass' => Page::className(), 'targetAttribute' => ['page_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'page_id' => 'Page ID',
            'created_at' => 'Создано',
            'message' => 'Комментарий',
        ];
    }
    
    /**
     * Вывод даты создания в виде строки для отображения
     * @return string
     */
    public function getCreatedDisplayed()
    {
        return date('d.m.Y H:i:s', $this->created_at);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPage()
    {
        return $this->hasOne(Page::className(), ['id' => 'page_id']);
    }
}

frontend/controllers/CommentController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Comment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            [
                'class' => 'yii\filters\AjaxFilter',
                'only' => ['create', 'delete']
            ],
        ];
    }

    /**
     * Создание нового комментария
     * 
     * @return mixed
     */
    public function actionCreate($page_id)
    {
        $model = new Comment();
        $model->page_id = $page_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->asJson(['result' => 'success']);
        }

        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }


    /**
     * Удаление комментария
     * 
     * @param integer $id
     * @return mixed Возвратит JSON
     * @throws NotFoundHttpException в случае ненахождения модели Комментария
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->asJson(['result' => 'success']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/comment/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Comment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comment-form">

    <?php $form = ActiveForm::begin([
        'options' => ['data-success' => 'successComment']
    ]); ?>

    <?= $form->field($model, 'message')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/comment/list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $Comments \frontend\models\Comment[] */
if (empty($Comments)) {
    return;
}
?>

<h4>Комментарии</h4>
<?php foreach ($Comments as $Comment): ?>
<div class="comment__block blockType">
    <div class="comment__body">
        <span><?= $Comment->getCreatedDisplayed(); ?></span>
        <?= $Comment->message; ?>
        <?= Html::tag('span', '', [
            'class' => 'delete text-danger glyphicon glyphicon-trash',
            'data' => [
                'confirm' => 'Вы действительно желаете удалитькомментарий?',
                'action' => Url::toRoute(['comment/delete', 'id' => $Comment->id]),
                'id' => $Page->id,
            ],
        ]); ?>
    </div>
</div>
<?php endforeach;