frontend/controllers/CommentController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Comment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            [
                'class' => 'yii\filters\AjaxFilter',
                'only' => ['create', 'delete']
            ],
        ];
    }

    /**
     * Создание нового комментария
     * 
     * @return mixed
     */
    public function actionCreate($page_id)
    {
        $model = new Comment();
        $model->page_id = $page_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->asJson(['result' => 'success']);
        }

        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }


    /**
     * Удаление комментария
     * 
     * @param integer $id
     * @return mixed Возвратит JSON
     * @throws NotFoundHttpException в случае ненахождения модели Комментария
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->asJson(['result' => 'success']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/PageController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Page;
use frontend\models\search\PageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            [
                'class' => 'yii\filters\AjaxFilter',
                'only' => ['create', 'update', 'delete']
            ],
        ];
    }

    /**
     * Отображение списка страни
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $Pages = $dataProvider->getModels();
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('pages', [
                'Pages' => $Pages
            ]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'Pages' => $Pages,
        ]);
    }

    /**
     * Создание страницы
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Page();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->asJson([
                'result' => 'success',
                'message' => 'Успешно добавлено',
                'class' => 'alert-success',
            ]);
        }
        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Обновление страницы
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->asJson([
                'result' => 'success',
                'message' => 'Успешно обновлено',
                'class' => 'alert-success',
            ]);
        }
        
        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Удаление страницы
     * 
     * @param integer $id
     * @return JSON
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->asJson(['result' => 'success']);
    }

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/page/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Alert;
/* @var $this yii\web\View */
/* @var $model frontend\models\Page */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="page-form" id="pageForm">
    <?= Alert::widget([
        'options' => [
            'class' => '',
            'id' => 'responseMessage'
        ],
        'body' => '',
    ]); ?>
    <?php $form = ActiveForm::begin([
        'options' => ['data-success' => 'successPage']
    ]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/page/index.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $Page \frontend\models\Page */ 

$this->title = 'Страницы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-index">
   
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
    <?php 
        Modal::begin([
            'header' => '',
            'toggleButton' => [
                'label' => 'Добавить страницу',
                'class' => 'btn btn-success contentModal',
                'id' => 'addPage',
                'data-action' => Url::toRoute('page/create'),
                'data-header' => 'Добавление новой страницы',
            ],
        ]);
        Modal::end();
    ?>
    </p>
    <div class="wrapPages">
        <?= $this->render('pages', ['Pages' => $Pages]); ?>
    </div>
    
</div>

frontend/views/page/pages.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
/* @var $Pages \frontend\models\Page[] */
?>

<?php foreach ($Pages as $Page): ?>
<div class="page__block blockType" data-page_id="<?= $Page->id; ?>">
    <div class="page__title">
        <?= $Page->title; ?>
        <?= Html::tag('span', '', [
            'class' => 'editPage contentModal glyphicon glyphicon-pencil',
            'data' => [
                'action' => Url::toRoute(['page/update', 'id' => $Page->id]),
                'header' => 'Редактирование страницы №'.$Page->id,
            ],
        ]); ?>
        <?= Html::tag('span', '', [
            'class' => 'delete text-danger glyphicon glyphicon-trash',
            'data' => [
                'confirm' => 'Вы действительно желаете удалить страницу и все её комментарии?',
                'action' => Url::toRoute(['page/delete', 'id' => $Page->id]),
                'id' => $Page->id,
            ],
        ]); ?>
    </div>
    <div class="page__body">
        <p>
            <span>Создано: <?= $Page->getCreatedDisplayed(); ?></span> 
            <?php if ($Page->isNotUpdated()): ?>
                <span>Обновлено: <?= $Page->getUpdatedDisplayed(); ?></span>
            <?php endif; ?>
        </p>
        <?php if (!empty($Page->body)): ?>
            <p><?= $Page->body; ?></p>
        <?php else: ?>
            <i>Нет содержимого</i>
        <?php endif; ?>
    </div>
    <div class="page__comment">
        <?= $this->render('../comment/list', [
            'Comments' => $Page->comments
        ]); ?>
    </div>
    <div class="commentform">
        <button class="btn btn-primary btn-xs addCommentForm"
                data-page_id="<?= $Page->id; ?>"
                data-action="<?= Url::toRoute(['comment/create', 'page_id' => $Page->id]) ?>">
            Комментировать
        </button>
    </div>
    <hr />
</div>
<?php endforeach; ?>